### ISSUE TITLE
Erro na remoção

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [BrunoGomesCoelho/Tabela-HashMIPS#12]
@GCyrillo 
Casos de teste que dá ruim:
- Inserção de X, remoção de X
- Inserção de 16, 32, remoção de 16---- (ver A)

Casos de teste que funcionam:
- Inserção de 16, 32, remoção de 32 ---- (A), esse da certo :/
- Inserção de 16, 32, 48, remoção de 32
- Inserção de 16, 32, 48, remoção de 48

**Comment by ghost** [comment]
Já tá pronto. Pensei que a estrutura era outra.
