### ISSUE TITLE
Modularizacão e Registradores

### ISSUE THREAD

**Issue by gmelodie** [BrunoGomesCoelho/Tabela-HashMIPS#2]
* Seria útil ter funcões como leValor, mod, etc... Quem faria isso?
* Ao iniciarmos uma funcão, é importante ter em mente que **nenhum** valor é garantido. Ou seja, devemos inicializar **todos** os registradores que usarmos.
* A pilha, assim como os registradores, deve estar vazia ao final da execucão de uma determinada funcão.

**Comment by BrunoGomesCoelho** [comment]
Mod o Cyrillo falou que tem pronto/vai fazer.

Já que a visualização é mais de boa pode deixar que faço essas funções básicas para todos, mas tirando a de leValor não sei qual fazer uma vez que para printar a pessoa teria que passar a string e chamar a função (2 linhas) e pra fazer na hora são 3 linhas, então acho que não vale a pena pra printar.

OBS: Para ter funções modularizadas, tem que chamar a função com JAL (jump and link) para setar o $ra e eu poder voltar para ele.
