### ISSUE TITLE
Número negativo como input

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [BrunoGomesCoelho/Tabela-HashMIPS#7]
Pessoal, nós(*cough* Cruz *cough*) vamos tratar o caso de o usuário tentar inserir um número negativo ou supomos que não há esse caso?

PS: Acho que na busca com certeza temos que considerar que o usuário pode tentar buscar por um número que não exista e os negativos devem estar inclusos nisso.

**Comment by gmelodie** [comment]
De acordo com a especificacão do trabalho, temos que tratar sim. Todos nós temos que tratar isso em todas as operacões. Sad....

**Comment by gmelodie** [comment]
Ah então, fiz a invalid input escrever "Entrada inválida" para poder ser usada sempre. Basta escrever:

```blt $suaEntrada, $zero, invalidInput```

e voilà

**Comment by BrunoGomesCoelho** [comment]
Boa! o @GCyrillo já trata isso acho (afinal, se é um número negativo ele não existe na remoção, pois você não inseriu.... hauhaushasu), só falta o Alex tratar também.
